Description of WAD_vbprint
WAD_vbprint
PURPOSE
------------------------------------------------------------------------
SYNOPSIS
function WAD_vbprint(arg, level)
DESCRIPTION
 ------------------------------------------------------------------------
 This WAD folder provides a "library" of helper functions written for IQC.
 NVKF WAD IQC software is a framework for automatic analysis of DICOM objects.
 Copyright 2012-2013  Joost Kuijer / jpa.kuijer@vumc.nl
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ------------------------------------------------------------------------
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
WAD_ErrorMsg ------------------------------------------------------------------------
WAD_checkMatchDefinition ------------------------------------------------------------------------
WAD_findMatchingSeries ------------------------------------------------------------------------
WAD_main ------------------------------------------------------------------------
WAD_parseAutoComment ------------------------------------------------------------------------
WAD_resultsAppendFigure ------------------------------------------------------------------------
WAD_resultsAppendFloat ------------------------------------------------------------------------
WAD_resultsAppendObject ------------------------------------------------------------------------
WAD_resultsAppendString ------------------------------------------------------------------------
WAD_runConfiguredAnalysis ------------------------------------------------------------------------
WAD_MG_AEC ------------------------------------------------------------------------
WAD_MG_flatField ------------------------------------------------------------------------
WAD_MR_B0_readGE_B0map ------------------------------------------------------------------------
WAD_MR_B0_readGE_VUMC_custom ------------------------------------------------------------------------
WAD_MR_B0_readPhilipsDoubleEcho ------------------------------------------------------------------------
WAD_MR_B0_readPhilips_B0map ------------------------------------------------------------------------
WAD_MR_B0_readSiemensPhaseDifference ------------------------------------------------------------------------
WAD_MR_B0_readSiemensServiceStimEcho ------------------------------------------------------------------------
WAD_MR_B0_readToshibaAAS ------------------------------------------------------------------------
WAD_MR_B0_uniformity ------------------------------------------------------------------------
WAD_MR_FMRI_weisskoff ------------------------------------------------------------------------
WAD_MR_SNR ------------------------------------------------------------------------
WAD_MR_SNR_MultiChannel ------------------------------------------------------------------------
WAD_MR_TxAmplFreq ------------------------------------------------------------------------
WAD_MR_geomXY ------------------------------------------------------------------------
WAD_MR_geomZ ------------------------------------------------------------------------
WAD_demo_actionOne ------------------------------------------------------------------------
WAD_demo_actionTwo ------------------------------------------------------------------------
SOURCE CODE
% ------------------------------------------------------------------------
% This WAD folder provides a "library" of helper functions written for IQC.
% NVKF WAD IQC software is a framework for automatic analysis of DICOM objects.
%
% Copyright 2012-2013  Joost Kuijer / jpa.kuijer@vumc.nl
%
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
% ------------------------------------------------------------------------
function WAD_vbprint(arg, level)
% vbprint is used for tracing / debugging / logging
% where the text output goes to, is defined by WAD.cfg.logverbose
global WAD
if (nargin ~= 2)
    level = 1;
end
if (level <= WAD.cfg.logverbose.level)
    if ( bitand( WAD.cfg.logverbose.mode, 1 ) && ( WAD.cfg.logverbose.fid ~= -1 ) )
        fprintf( WAD.cfg.logverbose.fid, '%s\n', arg );
    end
    if ( bitand( WAD.cfg.logverbose.mode, 2 ) )
        % print to screen
        fprintf( '%s\n', arg );
    end
end
return